language: python
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r requirements_dev.txt
  - pip install coveralls
  - pip install tox-travis
  - pip install .

script:
  - tox
  - py.test --cov=summarize
  - coverage report -m

after_success:
  - coveralls